### ISSUE TITLE
Standard too limiting?

### ISSUE THREAD

**Issue by alcinnz** [mozilla/repotheweb#11]
Looking at the standard today, I saw 2 parts which I question and want to know your opinion on. 
1. The standard states that protocol must be either a whitelisted one or be prefixed with "web+" (from looking at it before, I believe it was Google who pioneered this, but don't take my word for it). 

The reason I don't like it is because it seems heavy handed and limiting and would prefer browsers to let protocols develop independantly which can be smoothly implemented on either the web or native. It would be in my interest on PyOfWave if it were so. 

Also, by not following this, I don't think we'd be breaking the standard, just extending it. 
1. Among the reccomendations, it is encouraged for defaults not to be registered with a rph as it would confuse the user when they are directed to that site. I disagree as they've already said yes, and external links already exist. 

This also wouldn't break the standard as it is just a recommendation. 
## 

Obviously, I feel stronger on the first one, but I'm not commited to either. 

What do you think on these standards points? Should we implement them. 

P. S. I should have a new pull request ready tommorow with several small improvements like fixing broken target property of links and fallbacks (where I think the arguments in point 2 do apply).

**Comment by ozten** [comment]
1) I had the same reservations, but following web+ improves compatibility. You can always be more permissive in the future, but you can't go the other way without breaking backwards compatibility.

2) If this is a UX recommendation, what is there to change in the implementation?

**Comment by alcinnz** [comment]
1) A good compromise would be to shim all browsers that don't support the full standard, including the new remove and isRegistered methods (at the moment that's everyone). Until browsers support the full features, stick with a small whitelist and when they do support it, readjust. 

2) Remove the line from index.html that sets auto-redirect if there's only one registered RPH. 

I'll add that if I had a say, it'd be nice for the registration to be handled via a metatag with the APIs still available. However, this can be played with outside RepoTheWeb.

**Comment by alcinnz** [comment]
I just noticed that the limitations are only in the WHATWG standard, not the W3C. 

Makes sense, I don't think Berners-Lee would sign it.
