### ISSUE TITLE
iframe support

### ISSUE THREAD

**Issue by alcinnz** [mozilla/repotheweb#12]
I've been planning methods of extending support to iframes and JavaScript methods. 

Since iframes are more complex then links to support, I wanted to share especially that psuedocode before implementing. I've already refactored the simulate_rph function to just return the altered URL instead of directly handling link clicks. 
## iframes

To support iframes, I propose we include https://gist.github.com/384583 and use the following code:

```
function addFrame(frame) {
  frame.watch('src', util.simulate_rph);
  return frame;
}
for (var i; i < 1000; i++) // Support up to a 1000 frames
  frames.watch(i, addFrame);
```

I'm not fully confident I'm right on how Object.watch works, but I beleive the polyfill has enough support. 
## JavaScript calls

```
function decorURLFunc(obj, prop) {
  var super = obj[prop];
  obj[prop] = function() {
    arguments[0] = utils.simulate_rph(arguments[0]);
    return super.apply(this, arguments);
  }
}
decorURLFunc(window, 'open');
decorURLFunc(location, 'assign');
decorURLFunc(location, 'replace');
```
## 

Either of these methods should degrade gracefully.

**Comment by ozten** [comment]
From a user's perspective, what does this buy us?
And from a developer's perspective?

**Comment by alcinnz** [comment]
From a user's perspective, the iframes and JS calls are entirely different. 

The iframes would provide a method for embedding. For them, it'd be like seeing Google Maps boxes on the page (this is the major example, a map schema). Also in my use case, so waves can be embedded or linked to from a page. 

The JavaScript they wouldn't fully appreciate, but it would allow for more dynamic pages to use the technology. 

## 

From a developer's perspective, it can be summed up simply, more flexibility. 

And the exact same system to embed as well as link, just different tags.

**Comment by alcinnz** [comment]
Also, I wanted to bring this up as the JavaScript isn't the cleanest. 

The shim I pointed to depends on a nonstandard feature and won't have the broadest support as compared to links. I've thought on this for a while and don't know a better solution. 

As for changing the APIs, some browsers block overwriting APIs and it's considered a dangerous idea. However, in this case I think it's safe.

In either case, if it doesn't apply, I beleive it will just show an error as it would normally, so I think it's safe. But I wanted your opinion on code too.

**Comment by alcinnz** [comment]
UPDATE

I'm not using these approaches.

Instead for the APIs, I'm providing a small JavaScript function "location.url" which returns the passed string alterred by simulate_rph if the shim is in effect, otherwise the passed string. Requires a _slight_ change to JavaScript API usage, but is more reliable across browsers. 

~~As for frames, I'll just do translation of iframe src attribute onReady. Links with a target already work, but setting in JavaScript require a call to that function.~~ Doesn't work, frame loads first and something's not working right with onReady. I give up on doing this generically, developers now have the tools to do it directly on the iframe, so that'll have to be good enough. 

## 

I'm implementing this now and am confident with my new approach, so I'll close the issue.
