### ISSUE TITLE
Use RequireJS and a build script to create include.js

### ISSUE THREAD

**Issue by ozten** [mozilla/repotheweb#2]
Currently include.js has a copy/paste copy of jschannels. We should include this and have a build script that creates include.js as well as include.min.js. 

This will allow us to have two source files, 
- registerProtocolHandler.js - populates navigator.registerProtocolHandler
- simulate_rph.js - provides runtime implementation of rph logic

**Comment by ozten** [comment]
@alcinnz I started hacking on adding almond.js to clean up the code. It isn't finished enough to commit. Do you have experience with RequireJS or almod.js? Or any thoughts on JS modules. I think it will be a win.

**Comment by alcinnz** [comment]
Actually, I haven't minified before. I definitely plan to with PyOfWave. 

All I have to say is will help issue #7 and almond looks easy. 

 Maybe separate text in a separate file for eventual Internationalization. In the meantime it'll provide some convenience and can be used for formatting (say replace each %s with a following arguments and the code could call _("confirm_register", title, domain, scheme). Django (as in addons.mozilla.org engine) did something similar for JS i18n.)

**Comment by ozten** [comment]
Good call on JS i18n!

**Comment by ozten** [comment]
Broke code out using almond.js. Added r.js and instructions in README.
