### ISSUE TITLE
Websites must use include.js for non-native browsers

### ISSUE THREAD

**Issue by ozten** [mozilla/repotheweb#3]
Background: Assuming we're wrapping registerProtocolHandler (instead of xregisterProtocolHandler)...

Website authors will need to add the include.js tag to use non-standard links.

Otherwise, these links will only work in Firefox 3+ and Chrome 13+.

I don't think there is anyway around this. It's painful for adoption of this shim, since it's not purely declarative.

**Comment by benadida** [comment]
I don't think this is a problem. If we did anything else (e.g. Web Activities), this would also be true. We should encourage sites to just include the shim for now, it will disable itself once rph does the right thing.
