### ISSUE TITLE
Replace confirm and prompt JS calls with dialogs in new windows

### ISSUE THREAD

**Issue by ozten** [mozilla/repotheweb#4]
We should replace the following with dialog windows. They can have more features and look nicer, but are more secure than lightbox content dialogs.
- Prompt user to install with remember this choice option
- Prompt user to choose app to handle protocol when none of the installed handlers are default

**Comment by alcinnz** [comment]
Thinking mobile, I'd vote no.

Firstly, on these mobile devices only one page shows at a time and there's little screen real-estate. For this, a native dialogue would be most effective. As for the selection page, an intermediate page would be nice.

Secondly, on the desktop, I have attempted to open a window to look like a dialogue, but ran into the problem that the latest versions of FireFox and Chrome (and maybe others) insist on having a URL bar at the top. The appearance isn't customisable. 

Lastly, do we need a remember this choice option? Once a page registered, it shouldn't ask again. Visit another page which installs a protocol, the user should be aware. Personally, if we did have that option, I'd make it a bar at the top so it can install the protocol discretely and unobtrusively (UI wise, not unobtrusive javascript) tell the user. 

Still, if it reveals we do need more, I'm happy to change my mind.

**Comment by alcinnz** [comment]
Actually, sleeping on it, I like the idea of using a bar. It could read:

  This site has registered itself as handler for _scheme_ protocols [x remove] [\* options]

This not only subtly alerts the user, it also provides a nice place to put the options (the \* is meant to be a gear) link. 

As for the protocol selection, I'm thinking something like http://webintents.org/picker.html.

**Comment by ozten** [comment]
Right, these are good points. The mobile and desktop interaction could
be different, I just meant get ride of the weak alert/prompt stuff ;)

**Comment by alcinnz** [comment]
Especially the prompt?
