### ISSUE TITLE
Create Config dialog

### ISSUE THREAD

**Issue by ozten** [mozilla/repotheweb#5]
There should be a config dialog where you can:
- Delete individual PH
- Make a PH default
- See info about a PH

A barebones config to list and delete all PH already exists.

**Comment by alcinnz** [comment]
I think this could be developed quickly using John Resig's (founder and creator of jQuery) micro-templating:
http://ejohn.org/blog/javascript-micro-templating/.

It's a tiny bit of code for a great reward, more extreme than jQuery, although not as general usage.

**Comment by alcinnz** [comment]
I've got a wireframe at /designs/design in my repository. How do you like it? 

If you like it, I'll integrate it into bewehtoper.org, but I'm plenty happy to make changes.
